name: build image and deploy to fly.io

on:
  push:
    branches:
      - master

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  APP_NAME: fcm-push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      
      - name: Build image and push to registry
        run: |
          docker build -t ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --image ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
